name = "Wastemate"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE.md"
description = "Base theme for WasteMate sites"
homepage = "http://www.wastemate.com/"
tags = ["", ""]
features = ["", ""]
min_version = 0.13

[author]
  name = "Edison Code, LLC"
  homepage = "http://www.edisoncode.com/"